os: linux
language: go
go: "1.10"
dist: trusty
sudo: required
services:
  - docker

#env:
#  global:
#    - CGO_ENABLED=0

env:
  - GIT_BRANCH=$TRAVIS_BRANCH

#before_install:
#  - sudo apt-get update
#  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
#  - docker info
#  - docker version
#  - sudo pip install docker-compose
#  - docker-compose version

before_script:
  - docker login -u $ARTIFACT_REGISTRY_USERNAME -p $ARTIFACT_REGISTRY_PASSWORD

script:
  - make
  - make docker-tag

after_success:
  - make inspect

deploy:
  - provider: script
    script:
      - make docker-push
    skip_cleanup: true
    on:
      all_branches: true