package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"strconv"
	"time"

	"github.com/gorilla/mux"
	"github.com/namsral/flag"
)

var (
	proxy_url string
)


func ResponseProxyUrl(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	proxyAddr := fmt.Sprintf("%s/%s", proxy_url, vars["key"])

	w.Header().Add("Content-Type", "text/plain")
	hostname, err := os.Hostname()
	if err != nil {
		// handle err
		log.Fatalln(err)
	}
	// Get Response
	startRes := time.Now()
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
	resp, err := http.Get(proxyAddr)
	if err != nil {
		// handle err
		log.Fatalln(err)
	}
	defer resp.Body.Close()
	//fmt.Println(resp)
	fmt.Println(proxyAddr)
	endRes := time.Now()
	//fmt.Println("Response took", endRes.Sub(startRes))
	bodyString := ""
	if resp.StatusCode == http.StatusOK {
		bodyBytes, err := ioutil.ReadAll(resp.Body)
		bodyString = string(bodyBytes)
		if err != nil {
			fmt.Println(resp.StatusCode)
			log.Fatalln(err)
		}
		//print bodyString to stdout
		//fmt.Println(bodyString)

		//return to http
		fmt.Fprintf(w, "URL: %s, Response took: %s Code: %s, Hostname: %s,\nBody: %s", proxyAddr, endRes.Sub(startRes), strconv.Itoa(resp.StatusCode), hostname, bodyString)

	} else {
		//fmt.Println("stdout errors:", errs)
		w.WriteHeader(401)
		//prints to http client
		fmt.Fprintf(w, "Status code from %s: %s, hostname:", proxyAddr, strconv.Itoa(resp.StatusCode), hostname)
	}
}

func main() {
	flag.StringVar(&proxy_url, "proxy_url", "http://go-cassandra-checker.testing", "url address")
	flag.Parse()

	r := mux.NewRouter()
	r.HandleFunc("/info", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, "gangnam style")
	})

	//http.HandleFunc("/proxyinfo", ProxyInfo )
	r.HandleFunc("/proxy/{key}", ResponseProxyUrl)
	http.Handle("/", r)

	// Start the server
	http.ListenAndServe(":8080", nil)
}
